### ISSUE TITLE
face_detection_back

### ISSUE THREAD

**Issue by ttducqt** [hollance/BlazeFace-PyTorch#7]
Hello. Thanks for your work. 
I see that there is still a blazeface_back model at [https://github.com/google/mediapipe/blob/master/mediapipe/models/face_detection_back.tflite](url), how should i implement ?

**Comment by hollance** [comment]
Nice, I didn't know they had released this.

You will have to look at the two tflite files for the front and back model (using Netron, for example) to figure out where the differences are, and then change the PyTorch code.

**Comment by ttducqt** [comment]
Will you convert that model soon ? I can't wait it !!!  >.<

**Comment by hollance** [comment]
I have no plans to do this any time soon. I'm happy to take pull requests, though. ;-)

**Comment by ocastan** [comment]
Created the pull request you suggested. It was pretty straightforward thanks to your work (the back model is based on BlazeBlock) and your directions #12

**Comment by hollance** [comment]
Awesome, I've merged it into the repo.
